name: Microservice Updater
on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: Nesga-ARC/auth-microservice
          event-type: update_microservice
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
