name: Microservice Updater
on: push

jobs:
  update:
    strategy:
      matrix:
        repo: [
            'Nesga-ARC/auth-microservice',
            'Nesga-ARC/backoffice-microservice',
            'Nesga-ARC/nesga-socket',
            'Nesga-ARC/season-microservice',
            'Nesga-ARC/shop-microservice',
            'Nesga-ARC/user-microservice',
            'Nesga-ARC/watcher-microservice',
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Nesga-ARC/auth-microservice
          event-type: update-microservice
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'