name: Microservice Updater
on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: auth-microservice
          event-type: update-microservice
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'