name: Microservice Updater
on: push

jobs:
  build:
    name: Dispatch update to other repos
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
            repository: auth-microservice
            event-type: update_microservice
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
